# Generated by Django 6.0.3 on 2026-03-27 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('youtube_url', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.URLField(blank=True, default='')),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('channel_name', models.CharField(blank=True, default='', max_length=200)),
                ('tags', models.TextField(blank=True, default='[]')),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
